# Generated by Django 3.1.1 on 2020-11-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fandom', '0003_auto_20201130_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
